spring:
  application:
    name: user-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8100
ENERGY-SERVICE:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 800
#    MaxAutoRetries: 1   #在首次实例上的重试次数
#    MaxAutoRetriesNextServer: 2 #重试的实例次数
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000